Ability to specify additional files to be added to the chart
abrisco/rules_helm pull request #102
Opened 2024-10-01 15:51 UTC by dormidon

Try to address #74 

  * `files` attribute added to `helm_package`
  * it receives map from fileset to directory inside a chart where the whole fileset will be copied

Could be used as
```

filegroup(
    name = "configs",
    srcs = glob([
        "configs/**",
    ]),
)

helm_package(
    name = "package",
    files = {
        ":configs": "configs",
    },
    # rest of target parameters
)
```

In this case all file structure under `configs` directory will be copied to `configs` directory "inside" chart and would be available via `.Files.Get ("configs/my-config.yaml")`

2024-10-14 14:10 UTC, abrisco requested changes
Thanks for the change and sorry for the delay on the review! Out of curiosity, why not add the `files` field that builds a runfiles-like directory? It seems like that would make loading files more consistent but would also mean your charts will probably be different in and out of bazel if you're trying to continue to support both.

2024-10-14 17:29 UTC, dormidon commented
Hello!

Thank you for the feedback. 

> Out of curiosity, why not add the files field that builds a runfiles-like directory?

It seems that the answer is simple - because of lack of experience with Bazel :)
Could you please provide more details about your idea how it could be improved?

2024-10-15 04:41 UTC, abrisco requested changes
> Hello!
> 
> Thank you for the feedback.
> 
> > Out of curiosity, why not add the files field that builds a runfiles-like directory?
> 
> It seems that the answer is simple - because of lack of experience with Bazel :) Could you please provide more details about your idea how it could be improved?

I've left a comment with hopefully a useful suggestion!

2024-10-15 04:41 UTC, abrisco commented on helm/private/helm_package.bzl
> +    for ln in ctx.attr.files:
Kinda hard to use suggestions to suggest exactly what I'm thinking but:
```suggestion
    def _rlocationpath(file, workspace_name):
        if file.short_path.startswith("../"):
            return file.short_path[len("../"):]

        return "{}/{}".format(workspace_name, file.short_path)

    workspace_name = ctx.workspace_name

    def _rlocationpath_mapping(file):
        return "-add_files={}={}".format(file.path, _rlocationpath(file, workspace_name))

    args.add_all(ctx.files.files, map_each = _rlocationpath_mapping, allow_closure = True)
```

Anyone familiar with Runfiles APIs (e.g. [rust](https://github.com/bazelbuild/rules_rust/blob/95563e59098864e566395b6f0dbc7068f03ed0a8/tools/runfiles/runfiles.rs#L1-L31), [python](https://github.com/bazelbuild/rules_python/tree/0.36.0/python/runfiles)) should have an easy time finding files and not need to refer to the BUILD file target to understand what files are included and where to find them.

2025-02-05 19:29 UTC, abrisco commented
So sorry for the delay here, I've gone and implemented support for `files`. Some more implementation details can be found here:
- https://github.com/abrisco/rules_helm/pull/128#issuecomment-2637843708

I hope this is helpful (even after all this time) 😅

2025-02-05 19:29 UTC, closed without merging