remote_tag can be used as image ref
abrisco/rules_helm pull request #103
Opened 2024-10-02 09:10 UTC by dormidon

I would like to suggest some enhancements regarding `oci_push` image referencing and replacements in chart files. 

Sometimes it's more convenient to see meaningful Docker image tag in k8s specs instead of sha256 (otherwise we didn't add these tags to Docker images). In our case these tags are available from `oci_push` target (along with repository file). So we can try to use them in chart files replacements.

Besides that a lot of existing charts have separated settings for image repository and image tag. 
```
image:
   repository: docker.io/busybox
   tag: v1.2.3
```
So it would be useful to add separate replacements for these parameters so that people don't need to change structure of theirs charts in order to make them correctly packaged by `rules_helm`. Moreover, there are charts exist that use `image.tag` as a value for labels and annotations. 

The proposed solution works as follows:
  * if there is remote tags file in `oci_push` target, these information is included into `ImageInfo`
  * in a replacement group corresponding to `oci_push` target added next replacements:
     * `[@@]@<target name>.digest`
     * `[@@]@<target name>.repository`
     * `[@@]@<target name>.tag`
  * besides that in case of single `oci_push` target "well-known" substitution added
     * `bazel.image.url`
     * `bazel.image.repository`
     * `bazel.image.digest`
     * `bazel.image.tag` 

So that it's up to a user what substitution to use. 

Please, have a look at PR and thanks in advance!

2024-10-14 14:43 UTC, abrisco requested changes
Thanks! Could I get you to add an integration test? Perhaps just adding a new image dependency to `//tests/with_image_deps` and then use the tags resolver and add an entry to `//tests/with_image_deps:with_image_deps_regex_test`.

2024-10-14 17:30 UTC, dormidon commented
Yes, sure!
Thank you for the suggestion. Will try to do it quickly.

2024-10-14 21:24 UTC, dormidon commented
Test added - 70fbf0d95999f5f319d7143e5955345cc80d11e2

2024-10-15 04:30 UTC, abrisco approved these changes
Amazing! Thank you!

2024-10-15 04:30 UTC, merged

2024-10-15 07:37 UTC, sylvain-blot-sp commented
Amazing feature ! It opens the gate for selective deployment, thank you very much @dormidon !!!