Allow adding arbitrary files to helm chart
abrisco/rules_helm pull request #123
Opened 2024-12-16 22:40 UTC by purkhusid

## What
This is a continuation of https://github.com/abrisco/rules_helm/pull/102 with a bit nicer API

This allows the user to add arbitrary source of generated files to the helm chart at their desired location.

2024-12-17 10:00 UTC, purkhusid commented
@abrisco This is ready for review when you have the time

2024-12-17 10:04 UTC, purkhusid commented
Also fixes #106

2024-12-21 00:31 UTC, purkhusid commented
Also fixes #91

2025-01-06 13:17 UTC, purkhusid commented
@abrisco Do these changes look like something you would accept?

2025-01-06 16:06 UTC, abrisco requested changes
Thanks for the pull-request and sorry for the delay! My use of helm has always been pretty trivial, can you link me to any examples on how helm outside of Bazel would handle templates being in a directory outside of `templates`?

At a glance it seems like this change covers two things:
1. Fix the bug where any directory other than `templates` causes an infinite loop
2. Add a `files` attribute to `helm_package`.

Is that assessment correct? If so, it might be good to add an explicit test (something less than the kitchen sink 😅) maybe as it's own change.

Finally, I'm hoping to avoid turning `helm_package` into a macro. I know there's a convenience to being able to specify a dictionary of some arbitrary sources to a dedicated location, but I think the more maintainable interface would be for `helm_package` to do some sanity check that files are in the correct format or to apply some simple and consistent transform.

2025-01-07 09:22 UTC, purkhusid commented
> can you link me to any examples on how helm outside of Bazel would handle templates being in a directory outside of templates?
That´s the thing, helm does not support having templates outside of the `templates` folder. This is kind of at odds with how Bazel works since e.g. generated files will never be created in the same folder as files that are coming from the workspace. This PR changes the the handling of the template files so that all templates are copied into the `templates`. If the end user wants the templates folder to have some specific folder structure they can create that folder structure using e.g. filegroups before passing it into the `templates` attribute.

> At a glance it seems like this change covers two things:
>  * Fix the bug where any directory other than templates causes an infinite loop
>  * Add a files attribute to helm_package.

Yes, it also fixes #91 which was caused by packaging binary always using the same file name for the tar files that were generated which caused the dependencies to be overwritten. This only happens when the dependencies are also created by `rules_helm` and that's why it was not caught by the current dependency test.

> Finally, I'm hoping to avoid turning helm_package into a macro. I know there's a convenience to being able to specify a dictionary of some arbitrary sources to a dedicated location, but I think the more maintainable interface would be for helm_package to do some sanity check that files are in the correct format or to apply some simple and consistent transform.

I agree that it's unfortunate that Bazel does not provide the `attr` which allows us to create a good  API without macros. I could also change the API so that it just receives a list of files and then the end user can just create the folder structure themselves. E.g. 

```
```

2025-01-07 10:34 UTC, purkhusid commented
On second thought I'm not sure if a list of labels is a good api since dependency checking of directories is unsound. I think the best approach to use a macro if we want to have a good and flexible API that allows the end user to construct the helm chart contents in a way that they want.

2025-01-07 10:36 UTC, purkhusid commented
And TBH the `templates` attribute could use the same pattern as well since you can also have arbitrary folder structures inside the `teamplates` folder.

2025-01-17 18:08 UTC, purkhusid commented
@abrisco I changed the API to be just a simple list of files but with a check that makes sure that all the files that are in the list are relative to the root of the package that the helm chart target is in.

Could you take a look to see if this approach works for you?

2025-01-22 08:53 UTC, purkhusid commented
@abrisco Sorry about this PR becoming a dumping ground for various things. I'll split it up into multiple PRs if you agree with the changes/features that I'm adding.

I added make variable support to substitutions and also a the capability of reading files in substitutions.

2025-02-05 19:31 UTC, abrisco commented
Howdy! Super sorry for the delay here. I've gone and implemented support for `files`. Some more implementation details can be found here:
- https://github.com/abrisco/rules_helm/pull/128#issuecomment-2637843708

I've not checked that all the other fixes in this PR are covered by the changes I merged though (e.g. for https://github.com/abrisco/rules_helm/issues/91). Hopefully what I've added is useful to you and you can let me know if something else was inadvertently fixed (or broken!) 😅

2025-02-05 19:31 UTC, closed without merging