Support rules_oci + bzlmod
abrisco/rules_helm pull request #17
Opened 2023-08-18 06:54 UTC by opicaud

We can remove or keep the two first changes now or later, as they are "convenience" commits
This pull request concers:
- 1 fix about the replacement of templated value in the values.yaml
- the support of rules_oci
- the support of bzlmod

`image` rule must have been replaced by `oci_images` from commit b7fb0af as `rules_docker` has been removed to support bzlmod

2023-10-05 15:53 UTC, abrisco requested changes
Hi @opicaud, I'm so so sorry for the delay here. Some stuff came up in my personal life that was extremely time consuming. I think this change is fantastic! I had just one request but otherwise, after reading through the rules_oci issues you engaged in, I think this work is phenomenal. Thank you so much!

2023-10-05 15:53 UTC, abrisco commented on helm/helm.bzl
> +def helm_chart(name, oci_images = [], deps = None, tags = [], install_name = None, **kwargs):
I don't think you need to change the parameter name here, can you leave the interface the same so others don't need to make as many changes when udpating?

2023-10-06 12:56 UTC, abrisco commented on helm/helm.bzl
> +def helm_chart(name, oci_images = [], deps = None, tags = [], install_name = None, **kwargs):
this is actually something I can do post-merge

2023-10-06 13:53 UTC, abrisco approved these changes

2023-10-06 13:54 UTC, merged

2023-10-07 11:26 UTC, opicaud commented
Hey @abrisco 
Glad you are back :) and thanks to have reviewed and accepted this pull request.
To terminate this feature, I propose to:
- update the setup of the README with the explanation about how to install rules_helm via a MODULE.bazel
- publish rules_helm as component of the Bazel Central Registry --> see https://github.com/bazelbuild/bazel-central-registry

2023-10-07 20:51 UTC, abrisco commented
> Hey @abrisco 
> 
> Glad you are back :) and thanks to have reviewed and accepted this pull request.
> 
> To terminate this feature, I propose to:
> 
> - update the setup of the README with the explanation about how to install rules_helm via a MODULE.bazel
> 
> - publish rules_helm as component of the Bazel Central Registry --> see https://github.com/bazelbuild/bazel-central-registry

Would you be willing to update the README? I can look into updating the release pipeline to publish there.