Add helm_push_registry
abrisco/rules_helm pull request #30
Opened 2024-01-11 23:11 UTC by iDiogenes

* Add the ability to push a helm package to an oci registry

2024-01-11 23:17 UTC, iDiogenes commented
Opening this PR based on issue #28. While the issue talked about using ChartMuseum, I opted to go the route of pushing to an oci registry. Like with rules_oci, this commit leverages helm's internals for authentication when pushing to a registry. 

Also, something to consider, which I think might be a better approach, rather than using a new rule `helm_push_registry`, I could update this to extend `helm_push` to push the charts to an oci registry if a `registry_url` is provided. Personally, I think this is better approach, but I didn't want to go this route as we had not discussed it. Please let me know. 

Cheers!

2024-01-13 13:44 UTC, abrisco requested changes
This seems great, thanks! Just a couple of questions and some complaints from CI left 😄

2024-01-13 13:44 UTC, abrisco commented on helm/private/registrar/helm_registry.sh.template
> +eval {helm} push {chart} {registry_url}
should be able to exec, right?
```suggestion
exec {helm} push {chart} {registry_url}
```

2024-01-13 13:44 UTC, abrisco commented on helm/private/registrar/BUILD.bazel
> +        allow_empty = True,
does this need allow_empty?

2024-01-18 18:29 UTC, abrisco commented
I applied these changes on https://github.com/abrisco/rules_helm/pull/44, thank you so much for opening this PR!

2024-01-18 18:29 UTC, closed without merging

2024-01-18 18:48 UTC, iDiogenes commented
@abrisco - Sorry for the delay in resolving the feedback requests, I had a very busy week and was planing on getting to it this weekend. Thanks for taking care of it!

2024-01-18 19:09 UTC, abrisco commented
> @abrisco - Sorry for the delay in resolving the feedback requests, I had a very busy week and was planing on getting to it this weekend. Thanks for taking care of it! 

No worries at all! Someone had asked me about exactly this feature and besides a few nits your change looked perfect! Thought I'd do everyone a favor and rebase it and merge. Thank you again for the change!