Fix parsing of semver according to official specification
abrisco/rules_helm pull request #67
Opened 2024-02-14 12:19 UTC by cbullo

According to [Build Metadata](https://semver.org/#spec-item-10) it should be possible to use '+' sign to annotate version with build metadata.
However, the regex [packager.go:500](https://github.com/abrisco/rules_helm/blob/8b5f89988057e54cf395c71c3d05b6e58ed843db/helm/private/packager/packager.go#L500) doesn't allow that.

Using this string as a chart version will fail: 0.0.9+63-gf336c00.

2024-02-15 02:24 UTC, abrisco requested changes
Thanks! Do you think you could add some kind of regression testing for this? Maybe a unit test on the `packager.go` or perhaps an integration test where a package is built that has some crazy version that requires the full extent of this regex pattern? I would hate to break this in a future change 😅

2024-02-15 02:24 UTC, abrisco commented on helm/private/packager/packager.go
> +	re := regexp.MustCompile(`^(.*)-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-z
Dang! What a regex 😄

2024-02-15 10:22 UTC, cbullo commented
I'll write some tests, just need to learn Go for this :D 
Can you help me understand why the existing checks fail now?

2024-05-19 00:56 UTC, abrisco commented
I've gone and merged https://github.com/abrisco/rules_helm/pull/82 which should fix this issue, thank you for the pull request and sorry for any delays here 😄

2024-05-19 00:56 UTC, closed without merging