Reference resolved helm toolchain for the host
abrisco/rules_helm pull request #75
Opened 2024-04-25 01:39 UTC by kormide

This allows you to run the resolved helm toolchain as a local tool, e.g.

```bash
bazel run @helm//:helm ...
```

This is a technique we use in aspect_bazel_lib for several tools like jq: https://github.com/aspect-build/bazel-lib/blob/main/lib/private/jq_toolchain.bzl#L202

2024-04-25 12:47 UTC, abrisco requested changes
Thanks! Looks like the only outstanding issues are from buildifier, if you could fix those I'm happy to merge!
```
/home/runner/work/rules_helm/rules_helm/helm/extensions.bzl # reformat
/home/runner/work/rules_helm/rules_helm/helm/repositories.bzl # reformat
```

2024-04-25 17:11 UTC, kormide commented
Thanks! Updated.

2024-04-25 19:50 UTC, abrisco approved these changes

2024-04-25 19:50 UTC, merged

2024-05-12 04:10 UTC, abrisco commented
@kormide just a heads up: https://github.com/bazelbuild/bazel/issues/22303#issuecomment-2102122656